default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crypto_trader_api_development

test:
  <<: *default
  database: crypto_trader_api_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "crypto_trader_api_production") %>
    username: <%= ENV.fetch("DATABASE_USERNAME", "crypto_trader_api") %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

  cache:
    <<: *primary_production
    database: crypto_trader_api_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: crypto_trader_api_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: crypto_trader_api_production_cable
    migrations_paths: db/cable_migrate

# Automatically detect and use DATABASE_URL in production
production:
  url: <%= ENV["DATABASE_URL"] %>
